# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Busqueda(object):
    def setupUi(self, Busqueda):
        Busqueda.setObjectName("Busqueda")
        Busqueda.resize(869, 562)
        font = QtGui.QFont()
        font.setFamily("Nunito")
        Busqueda.setFont(font)
        Busqueda.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Busqueda)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 871, 511))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tituloArchivo = QtWidgets.QLabel(self.frame)
        self.tituloArchivo.setGeometry(QtCore.QRect(30, 10, 651, 41))
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(12)
        self.tituloArchivo.setFont(font)
        self.tituloArchivo.setText("")
        self.tituloArchivo.setObjectName("tituloArchivo")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(-10, 60, 891, 2))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.frameCanvas = QtWidgets.QWidget(self.frame)
        self.frameCanvas.setGeometry(QtCore.QRect(9, 69, 851, 441))
        self.frameCanvas.setObjectName("frameCanvas")
        self.btnDibujar = QtWidgets.QPushButton(self.frame)
        self.btnDibujar.setGeometry(QtCore.QRect(760, 20, 88, 23))
        self.btnDibujar.setObjectName("btnDibujar")
        self.inputArbol = QtWidgets.QLineEdit(self.frame)
        self.inputArbol.setGeometry(QtCore.QRect(710, 20, 31, 20))
        self.inputArbol.setObjectName("inputArbol")
        Busqueda.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Busqueda)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 869, 21))
        self.menubar.setObjectName("menubar")
        self.menuBFS = QtWidgets.QMenu(self.menubar)
        self.menuBFS.setObjectName("menuBFS")
        self.menuDFS = QtWidgets.QMenu(self.menubar)
        self.menuDFS.setObjectName("menuDFS")
        Busqueda.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Busqueda)
        self.statusbar.setObjectName("statusbar")
        Busqueda.setStatusBar(self.statusbar)
        self.actionBFS_1 = QtWidgets.QAction(Busqueda)
        self.actionBFS_1.setObjectName("actionBFS_1")
        self.actionBFS_02 = QtWidgets.QAction(Busqueda)
        self.actionBFS_02.setObjectName("actionBFS_02")
        self.actionBFS_03 = QtWidgets.QAction(Busqueda)
        self.actionBFS_03.setObjectName("actionBFS_03")
        self.menuBFS.addAction(self.actionBFS_1)
        self.menuBFS.addSeparator()
        self.menuBFS.addAction(self.actionBFS_02)
        self.menuBFS.addSeparator()
        self.menuBFS.addAction(self.actionBFS_03)
        self.menubar.addAction(self.menuBFS.menuAction())
        self.menubar.addAction(self.menuDFS.menuAction())

        self.retranslateUi(Busqueda)
        QtCore.QMetaObject.connectSlotsByName(Busqueda)

    def retranslateUi(self, Busqueda):
        _translate = QtCore.QCoreApplication.translate
        Busqueda.setWindowTitle(_translate("Busqueda", "Tarea1"))
        self.btnDibujar.setText(_translate("Busqueda", "Dibujar"))
        self.menuBFS.setTitle(_translate("Busqueda", "BFS"))
        self.menuDFS.setTitle(_translate("Busqueda", "DFS"))
        self.actionBFS_1.setText(_translate("Busqueda", "BFS-01"))
        self.actionBFS_02.setText(_translate("Busqueda", "BFS-02"))
        self.actionBFS_03.setText(_translate("Busqueda", "BFS-03"))
